# Generated by Django 3.0.5 on 2024-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologue', 'Cardiologue'), ('Dermatologue', 'Dermatologue'), ('Médecin urgentiste', 'Médecin urgentiste'), ('Pédiatre', 'Pédiatre'), ('Anesthésistes', 'Anesthésistes'), ('Cancerologue', 'Cancerologue'), ('Gynécologue', 'Gynécologue'), ('Neurologue', 'Neurologue'), ('Odontologiste', 'Odontologiste'), ('Chirurgien', 'Chirurgien'), ('Pneumologue', 'Pneumologue'), ('Psychiatre', 'Psychiatre'), ('Radiologue', 'Radiologue')], default='Cardiologue', max_length=50),
        ),
    ]
